In [1]:
import torch
from torch import utils
from torchvision import datasets, transforms

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [3]:
PATH = './SVHN'

In [5]:
train_ds = datasets.SVHN(PATH, download=True, transform=transforms.ToTensor())

In [31]:
train_ds[0][0][0]

tensor([[ 0.1294,  0.0588,  0.0588,  ...,  0.2824,  0.3216,  0.3490],
        [ 0.1098,  0.0549,  0.0549,  ...,  0.1569,  0.2627,  0.3255],
        [ 0.1569,  0.0706,  0.0627,  ...,  0.0902,  0.1373,  0.2824],
        ...,
        [ 0.3373,  0.3412,  0.3216,  ...,  0.4078,  0.4078,  0.4039],
        [ 0.3294,  0.3373,  0.3216,  ...,  0.4314,  0.4157,  0.4157],
        [ 0.3333,  0.3490,  0.3333,  ...,  0.4353,  0.4275,  0.4039]])

In [24]:
%%time
ms = torch.zeros((0,0))
ss = torch.zeros((0,0))
for i in range(len(train_ds)):
    x = train_ds[i][0].view(3,-1)
    m = x.mean(dim=1).unsqueeze(0)
    s = x.std(dim=1).unsqueeze(0)
    ms = torch.cat((ms, m))
    ss = torch.cat((ss, m))
mean = ms.mean(dim=0) 
std = ss.mean(dim=0)
print(mean, std)

tensor([ 0.4377,  0.4438,  0.4728]) tensor([ 0.4377,  0.4438,  0.4728])
CPU times: user 9.36 s, sys: 121 ms, total: 9.48 s
Wall time: 9.48 s


In [26]:
norm_ds = datasets.SVHN(PATH, download=True, transform=transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.4377,  0.4438,  0.4728), (0.4377,  0.4438,  0.4728))]))

Using downloaded and verified file: ./SVHN/train_32x32.mat


In [30]:
norm_ds[0][0][0]

tensor([[-0.7043, -0.8656, -0.8656,  ..., -0.3549, -0.2653, -0.2026],
        [-0.7491, -0.8746, -0.8746,  ..., -0.6416, -0.3997, -0.2564],
        [-0.6416, -0.8387, -0.8566,  ..., -0.7939, -0.6864, -0.3549],
        ...,
        [-0.2295, -0.2205, -0.2653,  ..., -0.0682, -0.0682, -0.0772],
        [-0.2474, -0.2295, -0.2653,  ..., -0.0145, -0.0503, -0.0503],
        [-0.2384, -0.2026, -0.2384,  ..., -0.0055, -0.0234, -0.0772]])